---
- name: Create tf2ds user
  user:
    home: "{{ tf2path }}"
    name: "{{ tf2user }}"
    state: present
    shell: /bin/false
- name: Allow anyone to read tf2ds files
  file:
    path: "{{ tf2path }}"
    state: directory
    mode: "0755"
